Repository cossacklabs/acra, pull requests merged in 2018-05, with the labels that each got.

#149 check tls config before handshake
  decryptor/mysql/packet.go
  decryptor/mysql/response_proxy.go
  decryptor/postgresql/pg_decryptor.go
  network/secure_session_wrapper.go
  network/tls_wrapper.go
  tests/test.py
Labels: core

#170 AcraWriter connector renaming (continue)
  cmd/acra-connector/acra-connector.go
  cmd/acra-server/acra-server.go
  cmd/acra_configui/acra_configui.go
  cmd/constants.go
  configs/acra-connector.yaml
Labels: refactoring

#171 add auth mode param
  cmd/acraproxy/acraproxy.go
  cmd/acraserver/acraserver.go
  network/tls_wrapper.go
  network/utils.go
  tests/test.py
Labels: core

#173 More components renaming
  .gitignore
  README.md
  acra-censor/acra-censor_configuration_provider.go
  acra-censor/acra-censor_implementation.go
  acra-censor/acra-censor_interfaces.go
  acra-censor/acra-censor_test.go
  acra-censor/handlers/blacklist_handler.go
  acra-censor/handlers/handlers_util.go
  acra-censor/handlers/handlers_util_test.go
  acra-censor/handlers/logging_handler.go
  acra-censor/handlers/whitelist_handler.go
  cmd/acra-addzone/acra-addzone.go
  cmd/acra-authmanager/acra_authmanager.go
  cmd/acra-keymaker/acra-keymaker.go
  cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
  cmd/acra-rollback/acra-rollback.go
  cmd/acra-server/acra-server.go
  cmd/acra-server/config.go
  cmd/acra-webconfig/acra-server_config_vars.go
  cmd/acra-webconfig/acra-webconfig.go
  cmd/acra-webconfig/static/img/favicon.ico
  cmd/acra-webconfig/static/index.html
  cmd/acra-webconfig/static/js/main.js
  cmd/constants.go
  cmd/utils_argon2.go
  configs/acra-addzone.yaml
  configs/acra-censor.example.yaml
  configs/acra-keymaker.yaml
  configs/acra-poisonrecordmaker.yaml
  configs/acra-rollback.yaml
  configs/acra-server.yaml
  configs/acra-webconfig.yaml
  configs/regenerate.sh
  decryptor/mysql/response_proxy.go
  examples/ruby/example_with_zone.rb
  keystore/server_keystore.go
  logging/event_codes.go
  tests/test.py
Labels: refactoring

#174 refactor cli args
  .circleci/integration.sh
  cmd/acra-addzone/acra-addzone.go
  cmd/acra-connector/acra-connector.go
  cmd/acra-keymaker/acra-keymaker.go
  cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
  cmd/acra-rollback/acra-rollback.go
  cmd/acra-server/acra-server.go
  cmd/acra-server/client_commands_session.go
  cmd/acra-server/config.go
  cmd/acra-server/listener.go
  cmd/acra-webconfig/acra-server_config_vars.go
  cmd/acra-webconfig/acra-webconfig.go
  cmd/utils.go
  configs/acra-addzone.yaml
  configs/acra-connector.yaml
  configs/acra-keymaker.yaml
  configs/acra-poisonrecordmaker.yaml
  configs/acra-rollback.yaml
  configs/acra-server.yaml
  configs/acra-webconfig.yaml
  configs/regenerate.sh
  decryptor/mysql/decryptor.go
  decryptor/mysql/decryptor_test.go
  docker/acra-connector.dockerfile
  docker/docker-compose.pgsql-nossl-server-ssession-connector.yml
  docker/docker-compose.pgsql-nossl-server-ssession-connector_zonemode.yml
  docker/docker-compose.pgsql-nossl-server-ssl-connector.yml
  docker/docker-compose.pgsql-nossl-server-ssl-connector_zonemode.yml
  docker/docker-compose.pgsql-ssl-server-ssl-connector.yml
  docker/docker-compose.pgsql-ssl-server-ssl_zonemode.yml
  tests/test.py
Labels: acra-censor, acra-connector, acra-poison_records_maker, acra-rollback, acra-server, acra-webconfig, core

#172 Add goroutine to censor for background logging
  acracensor/acracensor_configuration_provider.go
  acracensor/acracensor_implementation.go
  acracensor/acracensor_interfaces.go
  acracensor/acracensor_test.go
  acracensor/handlers/blacklist_handler.go
  acracensor/handlers/handlers_util.go
  acracensor/handlers/logging_handler.go
  acracensor/handlers/querycapture_handler.go
  acracensor/handlers/whitelist_handler.go
  cmd/acraserver/config.go
  logging/event_codes.go
Labels: acra-censor

#176 rename 'logger' to 'query_capture' for AcraCensor
  acra-censor/acra-censor_configuration_provider.go
  configs/acra-censor.example.yaml
Labels: acra-censor

#181 Script to generating keys and placing them into directory structure
  Makefile
  cmd/acra-keymaker/acra-keymaker.go
  scripts/generate-keys.sh
Labels: enhancement, infrastructure, key-management

#179 log errors in api handler
  cmd/acra-server/client_commands_session.go
  logging/event_codes.go
Labels: acra-server

#182 Fixed acra-keymaker GOPATH in generate-keys script
  scripts/generate-keys.sh
Labels: infrastructure

#186 return ErrorResponse on query block
  decryptor/postgresql/pg_decryptor.go
Labels: acra-server
