Repository cossacklabs/acra, pull requests merged in 2018-04, with the labels that each got.

#141 Mozh/t489 configui basicauth
  .gitignore
  cmd/acra_configui/Readme.md
  cmd/acra_configui/acra_configui.go
  cmd/acra_configui/acraserver_config_vars.go
  cmd/acra_configui/static/index.html
  cmd/acra_genauth/acra_genauth.go
  cmd/acra_genkeys/acra_genkeys.go
  cmd/acraserver/acraserver.go
  cmd/acraserver/auth.go
  cmd/acraserver/client_commands_session.go
  cmd/constants.go
  cmd/utils.go
  cmd/utils_argon2.go
  configs/acra_configui.yaml
  decryptor/mysql/decryptor_test.go
  keystore/filesystem_store.go
  keystore/keystore.go
  keystore/server_keystore.go
  logging/event_codes.go
  zone/zone_id_matcher_test.go
Labels: webui

#143 encrypt private keys
  cmd/acra_addzone/acra_addzone.go
  cmd/acra_genauth/acra_genauth.go
  cmd/acra_genkeys/acra_genkeys.go
  cmd/acra_genpoisonrecord/acra_genpoisonrecord.go
  cmd/acra_rollback/acra_rollback.go
  cmd/acraproxy/acraproxy.go
  cmd/acraserver/acraserver.go
  cmd/acraserver/client_commands_session.go
  keystore/filenames.go
  keystore/keystore.go
  keystore/keystore_test.go
  keystore/proxy_keystore.go
  keystore/server_keystore.go
  keystore/server_keystore_test.go
  tests/test.py
Labels: core

#146 Create docker-compose-pgsql-ssession
  Makefile
  docker/README.md
  docker/acra-build.dockerfile
  docker/acra_genkeys.dockerfile
  docker/acraserver.dockerfile
  docker/docker-compose-pgsql-ssession.yml
  docker/docker-compose.yml
Labels: docs, infrastructure

#147 refactor closing connections in tests
  cmd/acraserver/acraserver.go
  network/tls_wrapper.go
  tests/test.py
Labels: tests

#148 create folder if not exists for public keys
  keystore/server_keystore.go
Labels: core

#152 regenerate configs
  configs/acra_genkeys.yaml
  configs/acraserver.yaml
Labels: core, infrastructure

#153 Fix for acra-configui auth_off mode
  cmd/acra_configui/acra_configui.go
Labels: configui

#155 fix protocol parsing
  decryptor/mysql/column_field.go
  decryptor/mysql/packet.go
  decryptor/mysql/response_proxy.go
  decryptor/mysql/utils.go
Labels: core

#157 remove old readmes
  cmd/acra_configui/Readme.md
  cmd/acra_genpoisonrecord/Description.md
Labels: docs

#159 remove acra_rollback old readme
  cmd/acra_rollback/Readme.md
Labels: docs

#161 Acra ConfigUI integration tests
  .circleci/config.yml
  cmd/acra_configui/acra_configui.go
  cmd/acra_configui/static/index.html
  cmd/acra_configui/static/js/main.js
  cmd/acraserver/listener.go
  tests/requirements.txt
  tests/test.py
Labels: configui

#164 update acra version
  utils/version.go
Labels: infrastructure

#166 update ruby wrappers
  wrappers/ruby/acrawriter/acrawriter.gemspec
  wrappers/ruby/activerecord_acrawriter/activerecord_acrawriter.gemspec
  wrappers/ruby/activerecord_acrawriter/lib/activerecord_acrawriter.rb
Labels: acrawriter, ruby

#167 check netstat/awk dependencies
  cmd/acraproxy/acraproxy.go
Labels: infrastructure, proxy
