Repository cossacklabs/acra, pull requests merged in 2019-04, with the labels that each got.

#337 Fix image name in mysql-no-ssl compose file
  tests/docker/docker-compose-mysql-no-ssl.yml
Labels: bug

#338 support interval pgsql literals [T1024][T1007]
  cmd/acra-server/acra-server.go
  encryptor/queryDataEncryptor_test.go
  sqlparser/ast.go
  sqlparser/ast_methods.go
  sqlparser/ast_test.go
  sqlparser/dialect/dialect.go
  sqlparser/dialect/mysql/dialect.go
  sqlparser/dialect/mysql/dialect_test.go
  sqlparser/dialect/mysql/quoteHandler.go
  sqlparser/dialect/mysql/quoteHandler_test.go
  sqlparser/dialect/postgresql/dialect.go
  sqlparser/dialect/postgresql/dialect_test.go
  sqlparser/dialect/postgresql/quoteHandler.go
  sqlparser/dialect/postgresql/quoteHandler_test.go
  sqlparser/parse_next_test.go
  sqlparser/parse_test.go
  sqlparser/sql.go
  sqlparser/sql.y
  sqlparser/token.go
  sqlparser/token_test.go
  sqlparser/tracked_buffer.go
Labels: acra-censor, acra-server, mysql, postgresql, refactoring, sqlparser

#339 install correct pip and libpq-dev to build python dependencies
  .circleci/prepare.sh
Labels: tests
