Repository cossacklabs/acra, pull requests merged in 2022-10, with the labels that each got.

#586 Extend SQL syntax for searchable encryption
  CHANGELOG_DEV.md
  decryptor/postgresql/pending_packets.go
  encryptor/searchable_query_filter.go
  hmac/decryptor/hashQuery_test.go
  tests/test.py
Labels: acra-server

#588 Add feedback link to readme
  README.md
Labels: docs

#590 Support PostgreSQL double qouted columns
  encryptor/searchable_query_filter.go
  encryptor/searchable_query_filter_test.go
  encryptor/utils.go
  sqlparser/ast_test.go
  sqlparser/parse_test.go
  sqlparser/sql.go
  sqlparser/sql.y
  tests/test.py
Labels: acra-server, postgresql, sqlparser

#592 Extend searchable logic with joins
  CHANGELOG_DEV.md
  encryptor/dbDataCoder.go
  encryptor/queryDataEncryptor.go
  encryptor/searchable_query_filter.go
  encryptor/utils.go
  go.mod
  go.sum
  hmac/decryptor/hashQuery.go
  hmac/decryptor/hashQuery_test.go
  pseudonymization/tokenizeQuery.go
  pseudonymization/tokenizeQuery_test.go
  tests/ee_encryptor_config.yaml
  tests/ee_searchable_tokenization_config.yaml
  tests/test.py
Labels: acra-server

#595 Downgrade boto3 version to 1.23.10
  tests/requirements.txt
Labels: tests
